# Generated by Django 3.2.3 on 2021-05-25 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('height', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('base_hp', models.FloatField(blank=True, null=True)),
                ('base_attack', models.FloatField(blank=True, null=True)),
                ('base_defense', models.FloatField(blank=True, null=True)),
                ('base_special_attack', models.FloatField(blank=True, null=True)),
                ('base_special_defense', models.FloatField(blank=True, null=True)),
                ('base_speed', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
        ),
        migrations.CreateModel(
            name='Evolutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('evolution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='is_evolution_of', to='pokemon.pokemon')),
                ('preevolution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='is_preevolution_of', to='pokemon.pokemon')),
            ],
        ),
    ]
