# Generated by Django 3.2.3 on 2021-05-25 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evolutions',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='evolutions',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='updated_at',
        ),
    ]
