# Generated by Django 3.2.3 on 2021-05-25 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_auto_20210525_0222'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Evolutions',
            new_name='Evolution',
        ),
    ]
